VinylShopWeb/Areas/Admin/Controllers/LabelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VinylShop.DataAccess;
using VinylShop.DataAccess.Repository.IRepository;
using VinylShop.Models;
using VinylShop.Utility;

namespace VinylShopWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class LabelController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public LabelController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Label> objLabelList = _unitOfWork.Label.GetAll();
            return View(objLabelList);
        }
        //GET
        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Label obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Label.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Label created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var labelFromDbFirst = _unitOfWork.Label.GetFirstOrDefault(u => u.Id == id);
            if (labelFromDbFirst == null)
            {
                return NotFound();
            }
            return View(labelFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Label obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Label.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Label updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var labelFromDbFirst = _unitOfWork.Label.GetFirstOrDefault(u => u.Id == id);
            if (labelFromDbFirst == null)
            {
                return NotFound();
            }
            return View(labelFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Label.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Label.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Label deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

VinylShopWeb/Areas/Admin/Views/Label/Create.cshtml
@model Label

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Створити лейбл</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Створити</button>
		<a asp-controller="Label" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Повернутись до списку
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

VinylShopWeb/Areas/Admin/Views/Label/Delete.cshtml
@model Label

<form method="post" asp-action="DeletePOST">
	<input asp-for="Id" hidden/>
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Видалити лейбл</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Видалити</button>
		<a asp-controller="Label" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Повернутись до списку
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

VinylShopWeb/Areas/Admin/Views/Label/Edit.cshtml
@model Label

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Редагувати лейбл</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Оновити</button>
		<a asp-controller="Label" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Повернутись до списку
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

VinylShopWeb/Areas/Admin/Views/Label/Index.cshtml
@model IEnumerable<Label>
@{
    ViewData["Title"] = "Index";
}

<partial name="_Notification" />

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Список лейблів</h2>
		</div>
        <div class="col-6 text-end">
            <a asp-controller="Label" asp-action="Create" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Створити новий лейбл
			</a>
		</div>
	</div>
    <br /><br />
<table class="table table-bordered table-striped" style="width: 100%">
    <thead>
        <tr>
            <th>
                Назва лейблу
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Name
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Label" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                            <i class="bi bi-pencil-square"></i>Змінити
                        </a>
                        <a asp-controller="Label" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                            <i class="bi bi-trash-fill"></i>Видалити
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>