VinylShopWeb/Areas/Admin/Controllers/VinylPlateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VinylShop.DataAccess;
using VinylShop.DataAccess.Repository.IRepository;
using VinylShop.Models;
using VinylShop.Utility;

namespace VinylShopWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class VinylPlateController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        public VinylPlateController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        //GET
        public IActionResult Upsert(int? id)
        {
            VinylPlate vinylPlate = new VinylPlate();
            IEnumerable<SelectListItem> CategoryList = _unitOfWork.Category.GetAll().Select( u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            IEnumerable<SelectListItem> AuthorList = _unitOfWork.Author.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            IEnumerable<SelectListItem> LabelList = _unitOfWork.Label.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            if (id == null || id == 0)
            {
                // create
                ViewBag.CategoryList = CategoryList;
                ViewBag.AuthorList = AuthorList;
                ViewBag.LabelList = LabelList;
                return View(vinylPlate);
            }
            else
            {
                // update
                ViewBag.CategoryList = CategoryList;
                ViewBag.AuthorList = AuthorList;
                ViewBag.LabelList = LabelList;
                vinylPlate = _unitOfWork.VinylPlate.GetFirstOrDefault(u => u.Id == id);
                return View(vinylPlate);
            }
            
            
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(VinylPlate obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if(file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\vinylplates");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.ImageUrl = @"\images\vinylplates\" + fileName + extension;
                }
                if (obj.Id == 0)
                {
                    _unitOfWork.VinylPlate.Add(obj);
                }
                else
                {
                    _unitOfWork.VinylPlate.Update(obj);
                }
                _unitOfWork.Save();
                TempData["success"] = "Vinyl plate created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll(string price)
        {

            var vinylPlatesList = _unitOfWork.VinylPlate.GetAll(includeProperties: "Category,Author,Label");
            
            switch (price)
            {
                case "topFive":
                    vinylPlatesList = vinylPlatesList.Where(u => u.Price == 1570);
                    break;
                default:
                    break;
            }

            return Json(new { data = vinylPlatesList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.VinylPlate.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.VinylPlate.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Success" });
        }
        #endregion
    }
}

VinylShopWeb/Areas/Admin/Views/VinylPlate/Index.cshtml
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Список вінілових платівок</h2>
		</div>
        
        <div class="col-6 text-end">
            <a asp-controller="VinylPlate" asp-action="Upsert" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Створити нову платівку
			</a>
		</div>
	</div>
    <br /><br />
<table id="vinylData" class="table table-bordered table-striped" style="width: 100%">
    <thead>
        <tr>
            <th>
                Назва
            </th>
            <th>
                Жанр
            </th>
           <th>
                Автор
            </th>
            <th>
                Лейбл
            </th>
            <th>
                Формат
            </th>
            <th>
                Рік
            </th>
            <th>
                Код
            </th>
            <th>
                Ціна
            </th>
            <th>

            </th>
        </tr>
    </thead>
</table>
</div>

@section Scripts{
    <script src="~/js/vinylplate.js"></script>
}

VinylShopWeb/Areas/Admin/Views/VinylPlate/TopVinylPlates.cshtml
@model IEnumerable<VinylShop.Models.VinylPlate>

<div class="row pb-3">
	@foreach(var vinylPlate in Model)
	{
		<div class="col-lg-3 col-md-6">
			<div class="row p-2">
				<div class="col-12 p-1" style="border:1px solid #008cba; border-radius: 5px;">
					<div class="card">
						<img src="@vinylPlate.ImageUrl" class="card-img-top rounded"/>

						<div class="card-body">
						<div class="pl-1">
							<p class="card-title h5 text-primary">@vinylPlate.Title</p>
							<p class="card-title text-info">Автор: <b>@vinylPlate.Author.Name</b></p>
							<p class="card-title text-info">Лейбл: <b>@vinylPlate.Label.Name</b></p>
						</div>
						<div class="pl-1">
							@if (@vinylPlate.ListPrice == @vinylPlate.Price10){
									<p>Ціна: <b>₴@vinylPlate.ListPrice.ToString("0.00")</b></p>
								}
								else
								{
									<p>Ціна: <strike><b>₴@vinylPlate.ListPrice.ToString("0.00")</b></strike></p>
								}

						</div>
						<div class="pl-1">
							<p>Найменша ціна: <b>₴@vinylPlate.Price50.ToString("0.00")</b></p>
						</div>
						</div>
					</div>
					<div>
						<a asp-action="Details" class="btn btn-primary form-control" asp-route-vinylPlateId="@vinylPlate.Id">
							Детальніше
						</a>
					</div>
				</div> 
			</div>
		</div>
	}
</div>

VinylShopWeb/Areas/Admin/Views/VinylPlate/Upsert.cshtml
@model VinylPlate

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
	<input asp-for="Id" hidden />
	<input asp-for="ImageUrl" hidden />

	<div class="row">
		<div class="col-2 pt-4">
			<img src="@Model.ImageUrl"
			width="100%" style="border-radius:5px; border:1px solid #bbb9b9" />
		</div>
		<div class="col-10">
			<div class="border p-3 mt-4 row">
		<div class="col-12 pb-2">
			<h2 class="text-primary">@(Model.Id!=0?"Редагувати": "Створити") вінілову платівку</h2>
			<hr />
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="Title">Назва</label>
			<input asp-for="Title" class="form-control" />
			<span asp-validation-for="Title" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Code">Код</label>
			<input asp-for="Code" class="form-control" />
			<span asp-validation-for="Code" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Description">Опис</label>
			<textarea asp-for="Description" rows="3" class="form-control"></textarea>
			<span asp-validation-for="Description" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ListPrice">Ціна</label>
			<input asp-for="ListPrice" class="form-control" />
			<span asp-validation-for="ListPrice" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Year">Рік</label>
			<input asp-for="Year" class="form-control" />
			<span asp-validation-for="Year" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Country">Країна</label>
			<input asp-for="Country" class="form-control" />
			<span asp-validation-for="Country" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Format">Формат</label>
			<select asp-for="Format" class="form-select">
				<option disabled selected>--Обрати формат--</option>
				<option>EP</option>
				<option>LP</option>
				<option>SP</option>
			</select>
			<span asp-validation-for="Format" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Size">Розмір платівки</label>
			<input asp-for="Size" class="form-control" />
			<span asp-validation-for="Size" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Price">Ціна за 1-10 платівок</label>
			<input asp-for="Price" class="form-control" />
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Price10">Ціна за 10-50 платівок</label>
			<input asp-for="Price10" class="form-control" />
			<span asp-validation-for="Price10" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Price50">Ціна за 50+ платівок</label>
			<input asp-for="Price50" class="form-control" />
			<span asp-validation-for="Price50" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ImageUrl">Обкладинка платівки</label>
			<input type="file" name="file" class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="CategoryId">Жанр</label>
			<select asp-for="CategoryId" asp-items="ViewBag.CategoryList" class="form-select">
				<option disabled selected>--Обрати жанр--</option>
			</select>
			<span asp-validation-for="CategoryId" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AuthorId">Автор</label>
			<select asp-for="AuthorId" asp-items="ViewBag.AuthorList" class="form-select">
				<option disabled selected>--Обрати автора--</option>
			</select>
			<span asp-validation-for="AuthorId" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="LabelId">Лейбл</label>
			<select asp-for="LabelId" asp-items="ViewBag.LabelList" class="form-select">
				<option disabled selected>--Обрати лейбл--</option>
			</select>
			<span asp-validation-for="LabelId" class="text-danger"></span>
		</div>
		@if (Model.Id != 0)
			{
				<button type="submit" class="btn btn-primary" style="width:150px">Оновити</button>
			}
			else
			{
				<button type="submit" class="btn btn-primary" style="width:150px">Створити</button>
			}
			
		<a asp-controller="VinylPlate" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Повернутися до списку
		</a>
	</div>
</form>

@section Scripts{
	@{
			<partial name="_ValidationScriptsPartial" />
	}
}